# Generated by Django 5.1.2 on 2026-05-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParticipanteMapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comuna", models.CharField(max_length=100)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("ASISTENTE", "Asistente"),
                            ("EMPRENDEDOR", "Emprendedor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Participante del mapa",
                "verbose_name_plural": "Participantes del mapa",
                "ordering": ["-fecha", "comuna"],
            },
        ),
    ]
