# Generated by Django 5.1.2 on 2026-05-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MapaApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantemapa",
            name="origen",
            field=models.CharField(
                choices=[("EXCEL", "Excel"), ("MANUAL", "Manual")],
                default="EXCEL",
                max_length=10,
            ),
        ),
    ]
