# Generated by Django 5.1.2 on 2026-08-30 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MapaApp", "0002_participantemapa_origen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("fecha_evento", models.DateField()),
                (
                    "mostrar_desglose_por_tipo",
                    models.BooleanField(
                        default=True,
                        help_text="Si se desactiva, el mapa mostrará solo el total de asistentes.",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_evento", "nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="participantemapa",
            options={"ordering": ["-fecha", "comuna"]},
        ),
        migrations.AddField(
            model_name="participantemapa",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participantes",
                to="MapaApp.evento",
            ),
        ),
    ]
