# Generated by Django 5.1.2 on 2026-08-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MapaApp", "0003_evento_alter_participantemapa_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantemapa",
            name="fecha_hora_registro",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="participantemapa",
            name="origen",
            field=models.CharField(
                choices=[("EXCEL", "Excel")], default="EXCEL", max_length=10
            ),
        ),
    ]
