# Generated by Django 5.1.2 on 2026-09-01 23:17

import MapaApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MapaApp", "0005_configuracionmapa"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoMapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("imagen", models.ImageField(upload_to=MapaApp.models.logo_mapa_path)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Logo del mapa",
                "verbose_name_plural": "Logos del mapa",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="configuracionmapa",
            name="logo_activo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="MapaApp.logomapa",
            ),
        ),
    ]
