# Generated by Django 5.1.2 on 2026-09-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MapaApp", "0006_logomapa_configuracionmapa_logo_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="mostrar_solo_dia",
            field=models.BooleanField(
                default=False,
                help_text="Si se activa, la vista pública mostrará solamente los registros del día actual. Si se desactiva, mostrará todo el evento.",
            ),
        ),
    ]
