# Generated by Django 5.1.2 on 2026-08-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionMapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "columna_rol",
                    models.CharField(
                        default="Indique que tipo de participante es:", max_length=255
                    ),
                ),
                ("columna_comuna", models.CharField(default="Comuna", max_length=255)),
                (
                    "columna_fecha",
                    models.CharField(default="Hora de inicio", max_length=255),
                ),
                (
                    "escala_mapa",
                    models.CharField(
                        choices=[
                            ("LOG", "Logarítmica (recomendada)"),
                            ("LINEAL", "Lineal"),
                        ],
                        default="LOG",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del mapa",
                "verbose_name_plural": "Configuración del mapa",
            },
        ),
    ]
