# Generated by Django 5.1.2 on 2026-08-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracionMapa",
        ),
    ]
